feat: updateing action + minio

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -8,16 +8,9 @@ on:
     branches:
       - main
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
-  cancel-in-progress: true
-
 jobs:
   lint-test:
     runs-on: ubuntu-latest
-    timeout-minutes: 30
-    permissions:
-      contents: read
     outputs:
       changed: ${{ steps.list-changed.outputs.changed }}
       changedCharts: ${{ steps.list-changed.outputs.changedCharts }}
@@ -110,12 +103,6 @@ jobs:
       - name: Setup kubectl
         uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede # v4.0.1
 
-      - name: Login to Docker Hub to avoid rate limits
-        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
-        with:
-          username: ${{ secrets.REGISTRY_USER }}
-          password: ${{ secrets.REGISTRY_PASSWORD }}
-
       - name: Create kind cluster
         uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
         with:
@@ -160,3 +147,65 @@ jobs:
             # and without cleanup (let GitHub Actions handle it)
             ./test-charts.sh "$CHART_NAME" --no-cleanup
           done
+
+  publish-chart:
+    name: Publish Helm Chart
+    needs: [lint-test]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: azure/setup-helm@v4.3.1
+
+      - name: Checkout pull request branch
+        uses: actions/checkout@v5.0.0
+        with:
+          ref: ${{ github.head_ref }}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
+          fetch-depth: 0
+
+      - name: Set up chart-testing-action
+        uses: helm/chart-testing-action@v2.7.0
+
+      - name: Get changed charts
+        id: list-changed
+        run: |
+          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
+          if [[ -n "$changed" ]]; then
+            echo "Changed charts:"
+            echo "$changed"
+            echo "changed=$changed" >> $GITHUB_OUTPUT
+          else
+            echo "No chart changes detected"
+          fi
+
+      - name: Publish Helm chart to ttl
+        id: upload
+        if: ${{ steps.list-changed.outputs.changed }}
+        run: |
+          CHANGED_CHARTS="${{ steps.list-changed.outputs.changed }}"
+
+          RELEASED_CHARTS=""
+          for chart_directory in ${CHANGED_CHARTS//,/ }; do
+            CHART_NAME=${chart_directory#charts/}
+
+            cd $chart_directory
+
+            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
+            CHART_VERSION="0.1.0-${{ github.run_number }}"
+            APP_VERSION="unstable-${SHORT_SHA}"
+
+            helm dep update .
+            helm lint --strict .
+            helm package . --app-version=${APP_VERSION} --version=${CHART_VERSION}
+
+            # Push to GHCR
+            echo "Pushing Helm chart $CHART_NAME-$CHART_VERSION.tgz to oci://ttl.sh/${{ github.event.repository.name }}"
+            if helm push ./$CHART_NAME-$CHART_VERSION.tgz oci://ttl.sh/${{ github.event.repository.name }}; then
+              echo "Successfully released $CHART_NAME-$CHART_VERSION to ttl.sh"
+            else
+              echo "Failed to push $CHART_NAME-$CHART_VERSION to ttl.sh"
+              exit 1
+            fi
+
+            cd ${{ github.workspace }}
+          done
+          echo "released_charts=$RELEASED_CHARTS" >> "$GITHUB_OUTPUT"
